esphome:
  name: esp32s3-basictest

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: arduino

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_passwd

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32S3 Basictest"
    password: "esp32_ap"

captive_portal:

logger:
  level: DEBUG
  logs:
    sensor: INFO
    adc: INFO

interval:
  - interval: 5s
    then:
      - logger.log: Hello!
    